Gracefully handle missing DMI ID bios version or board name
This is admittedly a minor corner case: when run in a VM as opposed to real
hardware, /sys/class/dmi/id/board_name doesn't exist, and I'm seeing the
following error in the journal:

    Traceback (most recent call last):
      File "/usr/share/jupiter-fan-control/fancontrol.py", line 671, in <module>
        dmi_id = DmiId()
                 ^^^^^^^
      File "/usr/share/jupiter-fan-control/fancontrol.py", line 157, in __init__
        self.board_name = self.read("board_name")
                          ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/jupiter-fan-control/fancontrol.py", line 160, in read
        with open(self.id / identifier, "r", encoding="utf-8") as file:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/dmi/id/board_name'

This change results in an exception being raised at a different level
(NotImplementedError in the main function).